import '../../styles/globals.css';

export const metadata = {
  title: 'The blog',
  description: 'Generated by Next.js'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
);

export default RootLayout;
