/* eslint-disable import/extensions */
import Banner from '@/components/Banner';
import Header from '@/components/Header';

import '../../styles/globals.css';

export const metadata = {
  title: 'The blog',
  description: 'Generated by create next app'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className="max-w-7xl mx-auto">
      <Header />
      <Banner />
      {children}
    </body>
  </html>
);

export default RootLayout;
